[package]
name = "wlroots-sys"
version = "0.0.0"
authors = ["Timidger <APragmaticPlace@gmail.com>"]
description = "Bindgen generated low-level wlc wrapper"
keywords = ["wayland", "compositor", "bindings"]
categories = ["external-ffi-bindings"]
license = "MIT"
exclude = [".travis.yml"]

build = "build.rs"

[build-dependencies]
bindgen = "0.30.*"
meson = { version = "1.0", optional = true }
# For building shared lib
gcc = "0.3"
# This is for the simple example
gl_generator = "0.5.0"
# TODO Update once scanner fixes have been released
wayland-scanner = "0.12.*" #{ git = "https://github.com/smithay/wayland-rs", rev = "a54e033" }

[dependencies]
libc = "^0.2.*"
wayland-sys = {version = "0.12.*" }
wayland-server = { version = "0.12.*" }

[features]
default = ["static"]
static = ["meson"]
