[package]
name = "wlroots-sys"
version = "0.0.0"
authors = ["Timidger <APragmaticPlace@gmail.com>"]
description = "Bindgen generated low-level wlc wrapper"
keywords = ["wayland", "compositor", "bindings"]
categories = ["external-ffi-bindings"]
license = "MIT"
exclude = [".travis.yml"]

build = "build.rs"

[build-dependencies]
bindgen = "0.30.*"
meson = { version = "1.0", optional = true }

[dependencies]
libc = "^0.2.*"
wayland-sys = {version = "0.11.*" } #{ git = "https://github.com/Timidger/wayland-client-rs", features = ["client", "dlopen"] }
wayland-server = { version = "0.11.*" }

[features]
static = ["meson"]
