fn_brace_style = "SameLineWhere"
fn_args_density = "Vertical"
fn_args_layout = "Visual"
fn_call_style = "Visual"
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
report_todo = "Always"
report_fixme = "Always"
wrap_comments = true
use_try_shorthand = true
max_width = 100
trailing_comma = "Never"
attributes_on_same_line_as_field = true
attributes_on_same_line_as_variant = true
condense_wildcard_suffixes = true
error_on_line_overflow = true
force_explicit_abi = true
format_strings = true
generics_indent = "Visual"
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Mixed"
match_block_trailing_comma = false
multiline_closure_forces_block = true
multiline_match_arm_forces_block = true
newline_style = "Unix"
normalize_comments = false
take_source_hints = true
trailing_semicolon = false
where_density = "Vertical"
write_mode = "Overwrite"
