language: rust
sudo: "required"
compilers:
  - gcc
  - clang
cache: cargo
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
arch:
  packages:
    - meson
    - ninja
    - wayland
    - wayland-protocols
    - mesa
    - libinput
    - pixman
    - libxkbcommon
    - libcap
    - rust
    - clang
  script:
    - export RUST_BACKTRACE=full
    - cargo install rustfmt
    - git submodule update --init --recursive

    # Build wlroots
    - cd wlroots-sys; cd wlroots; meson build; ninja -C build

    # Build wlroots-sys
    - cd wlroots-sys; cargo build --verbose --features static

    # Build wlroots-rs
    - cargo build --verbose
    - cargo fmt -- --write-mode=diff
    - cargo build --examples
    - cargo doc

before_script:
  - which rustfmt || cargo install rustfmt
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

