language: rust
sudo: "required"
compilers:
  - gcc
  - clang
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
arch:
  packages:
    - meson
    - ninja
    - wayland
    - wayland-protocols
    - mesa
    - libinput
    - pixman
    - libxkbcommon
    - libcap
  script:
    - export RUST_BACKTRACE=full
    - ls -R
    - git submodule update --init --recursive
    - cd wlroots-sys
    - cd wlroots
    # Build wlroots
    - meson build
    - ninja -C build

    # Build wlroots-sys
    - cd ../
    - cargo build --verbose --features static
    - cargo test --features static
    - cargo doc

    - cd ../
    # Build wlroots-rs
    - cargo build --verbose
    - cargo fmt -- --write-mode=diff
    - cargo build --examples
    - cargo test
    - cargo doc

before_script:
  - which rustfmt || cargo install rustfmt
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

