language: rust
sudo: "required"
dist: trusty
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
  slack: way-cooler:bf5hNqMVmTgFpHo3a3vgZ4Lu
before_install:
  - sudo add-apt-repository -y ppa:wayland.admin/daily-builds
  - sudo apt-get update -qq
  - sudo apt-get install -y libwayland-dev libwayland-protocols-dev libegl1-mesa-dev libgles2-mesa-dev udev asciidoc libudev-dev libinput-dev libxkbcommon-dev libcap-dev libgbm-dev systemd libdbus-1-dev ninja-build
before_script:
  -  which rustfmt || cargo install rustfmt
script:
  - export RUST_BACKTRACE=full
  - git submodule update --init --recursive
  - cd wlroots-sys
  - cd wlroots
  # Build wlroots
  - meson build
  - ninja -C build
  
  # Build wlroots-sys
  - cd ../
  - cargo build --verbose --features static
  - cargo test --features static
  - cargo doc

  - cd ../
  # Build wlroots-rs
  - cargo build --verbose
  - cargo fmt -- --write-mode=diff
  - cargo test
  - cargo doc

