language: rust
sudo: "required"
compilers:
  - gcc
  - clang
cache: rustup
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
arch:
  packages:
    - meson
    - ninja
    - wayland
    - wayland-protocols
    - mesa
    - libinput
    - pixman
    - libxkbcommon
    - xcb-util-image
    - libcap
    - rustup
    - clang
  script:
    - rustup install stable
    # For rustfmt
    - rustup default stable
    - export RUST_BACKTRACE=full
    - git submodule update --init --recursive

    # Build wlroots
    - cd wlroots-sys; cd wlroots; meson build; ninja -C build

    # Build wlroots-sys
    - cd wlroots-sys; cargo build --verbose --features static

    # Build wlroots-rs
    - cargo build --verbose
    - cargo build --examples
    - cargo doc

    # Test everything
    - cargo test --all

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

